// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>MSCIBarra_EquityIndex</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MSCIBarra_EquityIndex
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xml.mscibarra.com/ns/msci/deal/D15D")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.mscibarra.com/ns/msci/deal/D15D", IsNullable = false)]
    public partial class package_D15D
    {

        private List<package_D15DEntry> dataset_D15DField;

        public package_D15D()
        {
            this.dataset_D15DField = new List<package_D15DEntry>();
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable = false)]
        public List<package_D15DEntry> dataset_D15D
        {
            get
            {
                return this.dataset_D15DField;
            }
            set
            {
                this.dataset_D15DField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xml.mscibarra.com/ns/msci/deal/D15D")]
    public partial class package_D15DEntry
    {

        private System.DateTime calc_dateField;

        private string security_nameField;

        private decimal msci_timeseries_codeField;

        private decimal msci_issuer_codeField;

        private decimal msci_security_codeField;

        private string sedolField;

        private string cusipField;

        private string isinField;

        private string iSO_country_symbolField;

        private decimal dM_universe_flagField;

        private decimal eM_universe_flagField;

        private decimal sectorField;

        private decimal sector_next_dayField;

        private bool sector_next_dayFieldSpecified;

        private decimal industry_groupField;

        private decimal industry_group_next_dayField;

        private bool industry_group_next_dayFieldSpecified;

        private decimal industryField;

        private decimal industry_next_dayField;

        private bool industry_next_dayFieldSpecified;

        private decimal sub_industryField;

        private decimal sub_industry_next_dayField;

        private bool sub_industry_next_dayFieldSpecified;

        private decimal non_local_listing_flagField;

        private bool non_local_listing_flagFieldSpecified;

        private decimal publication_flagField;

        private bool publication_flagFieldSpecified;

        private decimal priceField;

        private decimal value_of_quotationField;

        private string price_markerField;

        private string price_ISO_currency_symbolField;

        private string price_ISO_ccy_symbol_next_dayField;

        private decimal sec_idx_eod00d_locField;

        private decimal price_adjustment_factorField;

        private bool price_adjustment_factorFieldSpecified;

        private string adjustment_commentsField;

        private decimal prelim_price_adj_fact_nxt_dayField;

        private bool prelim_price_adj_fact_nxt_dayFieldSpecified;

        private string adjustment_comments_next_dayField;

        private decimal eod_number_of_shares_todayField;

        private bool eod_number_of_shares_todayFieldSpecified;

        private decimal eod_number_of_shares_next_dayField;

        private bool eod_number_of_shares_next_dayFieldSpecified;

        private decimal closing_number_of_sharesField;

        private bool closing_number_of_sharesFieldSpecified;

        private decimal foreign_inclusion_factorField;

        private bool foreign_inclusion_factorFieldSpecified;

        private decimal foreign_inc_factor_next_dayField;

        private bool foreign_inc_factor_next_dayFieldSpecified;

        private decimal domestic_inclusion_factorField;

        private bool domestic_inclusion_factorFieldSpecified;

        private decimal domestic_inc_factor_next_dayField;

        private bool domestic_inc_factor_next_dayFieldSpecified;

        private decimal limited_investability_factorField;

        private bool limited_investability_factorFieldSpecified;

        private decimal foreign_ownership_limitField;

        private bool foreign_ownership_limitFieldSpecified;

        private decimal family_std_flagField;

        private bool family_std_flagFieldSpecified;

        private decimal family_std_flag_next_dayField;

        private bool family_std_flag_next_dayFieldSpecified;

        private decimal family_std_dom_flagField;

        private bool family_std_dom_flagFieldSpecified;

        private decimal family_std_dom_flag_next_dayField;

        private bool family_std_dom_flag_next_dayFieldSpecified;

        private decimal family_large_flagField;

        private bool family_large_flagFieldSpecified;

        private decimal family_large_flag_next_dayField;

        private bool family_large_flag_next_dayFieldSpecified;

        private decimal pro_forma_family_large_flagField;

        private bool pro_forma_family_large_flagFieldSpecified;

        private decimal family_mid_flagField;

        private bool family_mid_flagFieldSpecified;

        private decimal family_mid_flag_next_dayField;

        private bool family_mid_flag_next_dayFieldSpecified;

        private decimal pro_forma_family_mid_flagField;

        private bool pro_forma_family_mid_flagFieldSpecified;

        private string iSO_country_symbol_next_dayField;

        private decimal value_of_quotation_next_dayField;

        private bool value_of_quotation_next_dayFieldSpecified;

        private decimal pro_forma_FIFField;

        private bool pro_forma_FIFFieldSpecified;

        private decimal pro_forma_DIFField;

        private bool pro_forma_DIFFieldSpecified;

        private decimal pro_forma_family_std_flagField;

        private bool pro_forma_family_std_flagFieldSpecified;

        private decimal pro_forma_family_std_dom_flagField;

        private bool pro_forma_family_std_dom_flagFieldSpecified;

        private decimal price_return_locField;

        private bool price_return_locFieldSpecified;

        private decimal price_return_usdField;

        private bool price_return_usdFieldSpecified;

        private decimal gross_return_locField;

        private bool gross_return_locFieldSpecified;

        private decimal gross_return_usdField;

        private bool gross_return_usdFieldSpecified;

        private decimal net_return_intl_locField;

        private bool net_return_intl_locFieldSpecified;

        private decimal net_return_intl_usdField;

        private bool net_return_intl_usdFieldSpecified;

        private decimal initial_mkt_cap_usdField;

        private bool initial_mkt_cap_usdFieldSpecified;

        private decimal initial_mkt_cap_usd_next_dayField;

        private bool initial_mkt_cap_usd_next_dayFieldSpecified;

        private decimal initial_mkt_cap_locField;

        private bool initial_mkt_cap_locFieldSpecified;

        private decimal initial_mkt_cap_loc_next_dayField;

        private bool initial_mkt_cap_loc_next_dayFieldSpecified;

        private decimal company_full_mktcapField;

        private bool company_full_mktcapFieldSpecified;

        private decimal std_IIFField;

        private bool std_IIFFieldSpecified;

        private decimal std_IIF_next_dayField;

        private bool std_IIF_next_dayFieldSpecified;

        private decimal pro_forma_std_IIFField;

        private bool pro_forma_std_IIFFieldSpecified;

        private decimal family_large_dom_flagField;

        private bool family_large_dom_flagFieldSpecified;

        private decimal family_large_dom_flag_next_dayField;

        private bool family_large_dom_flag_next_dayFieldSpecified;

        private decimal pro_forma_family_large_dom_flgField;

        private bool pro_forma_family_large_dom_flgFieldSpecified;

        private decimal pro_forma_sub_industryField;

        private bool pro_forma_sub_industryFieldSpecified;

        private decimal pro_forma_eod_number_of_sharesField;

        private bool pro_forma_eod_number_of_sharesFieldSpecified;

        private decimal family_mid_dom_flagField;

        private bool family_mid_dom_flagFieldSpecified;

        private decimal family_mid_dom_flag_next_dayField;

        private bool family_mid_dom_flag_next_dayFieldSpecified;

        private decimal pro_forma_family_mid_dom_flgField;

        private bool pro_forma_family_mid_dom_flgFieldSpecified;

        private decimal unadj_market_cap_today_usdolField;

        private bool unadj_market_cap_today_usdolFieldSpecified;

        private decimal adj_market_cap_usdolField;

        private bool adj_market_cap_usdolFieldSpecified;

        private decimal fm_universe_flagField;

        private bool fm_universe_flagFieldSpecified;

        private decimal gcc_universe_flagField;

        private bool gcc_universe_flagFieldSpecified;

        private string rICField;

        private string bb_tickerField;

        private string sedol_next_dayField;

        private string share_classField;

        private string share_typeField;

        private string alternate_listingField;

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime calc_date
        {
            get
            {
                return this.calc_dateField;
            }
            set
            {
                this.calc_dateField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string security_name
        {
            get
            {
                return this.security_nameField;
            }
            set
            {
                this.security_nameField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal msci_timeseries_code
        {
            get
            {
                return this.msci_timeseries_codeField;
            }
            set
            {
                this.msci_timeseries_codeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal msci_issuer_code
        {
            get
            {
                return this.msci_issuer_codeField;
            }
            set
            {
                this.msci_issuer_codeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal msci_security_code
        {
            get
            {
                return this.msci_security_codeField;
            }
            set
            {
                this.msci_security_codeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sedol
        {
            get
            {
                return this.sedolField;
            }
            set
            {
                this.sedolField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cusip
        {
            get
            {
                return this.cusipField;
            }
            set
            {
                this.cusipField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string isin
        {
            get
            {
                return this.isinField;
            }
            set
            {
                this.isinField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ISO_country_symbol
        {
            get
            {
                return this.iSO_country_symbolField;
            }
            set
            {
                this.iSO_country_symbolField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal DM_universe_flag
        {
            get
            {
                return this.dM_universe_flagField;
            }
            set
            {
                this.dM_universe_flagField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal EM_universe_flag
        {
            get
            {
                return this.eM_universe_flagField;
            }
            set
            {
                this.eM_universe_flagField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal sector
        {
            get
            {
                return this.sectorField;
            }
            set
            {
                this.sectorField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal sector_next_day
        {
            get
            {
                return this.sector_next_dayField;
            }
            set
            {
                this.sector_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sector_next_daySpecified
        {
            get
            {
                return this.sector_next_dayFieldSpecified;
            }
            set
            {
                this.sector_next_dayFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal industry_group
        {
            get
            {
                return this.industry_groupField;
            }
            set
            {
                this.industry_groupField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal industry_group_next_day
        {
            get
            {
                return this.industry_group_next_dayField;
            }
            set
            {
                this.industry_group_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool industry_group_next_daySpecified
        {
            get
            {
                return this.industry_group_next_dayFieldSpecified;
            }
            set
            {
                this.industry_group_next_dayFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal industry
        {
            get
            {
                return this.industryField;
            }
            set
            {
                this.industryField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal industry_next_day
        {
            get
            {
                return this.industry_next_dayField;
            }
            set
            {
                this.industry_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool industry_next_daySpecified
        {
            get
            {
                return this.industry_next_dayFieldSpecified;
            }
            set
            {
                this.industry_next_dayFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal sub_industry
        {
            get
            {
                return this.sub_industryField;
            }
            set
            {
                this.sub_industryField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal sub_industry_next_day
        {
            get
            {
                return this.sub_industry_next_dayField;
            }
            set
            {
                this.sub_industry_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sub_industry_next_daySpecified
        {
            get
            {
                return this.sub_industry_next_dayFieldSpecified;
            }
            set
            {
                this.sub_industry_next_dayFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal non_local_listing_flag
        {
            get
            {
                return this.non_local_listing_flagField;
            }
            set
            {
                this.non_local_listing_flagField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool non_local_listing_flagSpecified
        {
            get
            {
                return this.non_local_listing_flagFieldSpecified;
            }
            set
            {
                this.non_local_listing_flagFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal publication_flag
        {
            get
            {
                return this.publication_flagField;
            }
            set
            {
                this.publication_flagField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool publication_flagSpecified
        {
            get
            {
                return this.publication_flagFieldSpecified;
            }
            set
            {
                this.publication_flagFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal value_of_quotation
        {
            get
            {
                return this.value_of_quotationField;
            }
            set
            {
                this.value_of_quotationField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string price_marker
        {
            get
            {
                return this.price_markerField;
            }
            set
            {
                this.price_markerField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string price_ISO_currency_symbol
        {
            get
            {
                return this.price_ISO_currency_symbolField;
            }
            set
            {
                this.price_ISO_currency_symbolField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string price_ISO_ccy_symbol_next_day
        {
            get
            {
                return this.price_ISO_ccy_symbol_next_dayField;
            }
            set
            {
                this.price_ISO_ccy_symbol_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal sec_idx_eod00d_loc
        {
            get
            {
                return this.sec_idx_eod00d_locField;
            }
            set
            {
                this.sec_idx_eod00d_locField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal price_adjustment_factor
        {
            get
            {
                return this.price_adjustment_factorField;
            }
            set
            {
                this.price_adjustment_factorField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool price_adjustment_factorSpecified
        {
            get
            {
                return this.price_adjustment_factorFieldSpecified;
            }
            set
            {
                this.price_adjustment_factorFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string adjustment_comments
        {
            get
            {
                return this.adjustment_commentsField;
            }
            set
            {
                this.adjustment_commentsField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal prelim_price_adj_fact_nxt_day
        {
            get
            {
                return this.prelim_price_adj_fact_nxt_dayField;
            }
            set
            {
                this.prelim_price_adj_fact_nxt_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prelim_price_adj_fact_nxt_daySpecified
        {
            get
            {
                return this.prelim_price_adj_fact_nxt_dayFieldSpecified;
            }
            set
            {
                this.prelim_price_adj_fact_nxt_dayFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string adjustment_comments_next_day
        {
            get
            {
                return this.adjustment_comments_next_dayField;
            }
            set
            {
                this.adjustment_comments_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal eod_number_of_shares_today
        {
            get
            {
                return this.eod_number_of_shares_todayField;
            }
            set
            {
                this.eod_number_of_shares_todayField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eod_number_of_shares_todaySpecified
        {
            get
            {
                return this.eod_number_of_shares_todayFieldSpecified;
            }
            set
            {
                this.eod_number_of_shares_todayFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal eod_number_of_shares_next_day
        {
            get
            {
                return this.eod_number_of_shares_next_dayField;
            }
            set
            {
                this.eod_number_of_shares_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eod_number_of_shares_next_daySpecified
        {
            get
            {
                return this.eod_number_of_shares_next_dayFieldSpecified;
            }
            set
            {
                this.eod_number_of_shares_next_dayFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal closing_number_of_shares
        {
            get
            {
                return this.closing_number_of_sharesField;
            }
            set
            {
                this.closing_number_of_sharesField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool closing_number_of_sharesSpecified
        {
            get
            {
                return this.closing_number_of_sharesFieldSpecified;
            }
            set
            {
                this.closing_number_of_sharesFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal foreign_inclusion_factor
        {
            get
            {
                return this.foreign_inclusion_factorField;
            }
            set
            {
                this.foreign_inclusion_factorField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool foreign_inclusion_factorSpecified
        {
            get
            {
                return this.foreign_inclusion_factorFieldSpecified;
            }
            set
            {
                this.foreign_inclusion_factorFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal foreign_inc_factor_next_day
        {
            get
            {
                return this.foreign_inc_factor_next_dayField;
            }
            set
            {
                this.foreign_inc_factor_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool foreign_inc_factor_next_daySpecified
        {
            get
            {
                return this.foreign_inc_factor_next_dayFieldSpecified;
            }
            set
            {
                this.foreign_inc_factor_next_dayFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal domestic_inclusion_factor
        {
            get
            {
                return this.domestic_inclusion_factorField;
            }
            set
            {
                this.domestic_inclusion_factorField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool domestic_inclusion_factorSpecified
        {
            get
            {
                return this.domestic_inclusion_factorFieldSpecified;
            }
            set
            {
                this.domestic_inclusion_factorFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal domestic_inc_factor_next_day
        {
            get
            {
                return this.domestic_inc_factor_next_dayField;
            }
            set
            {
                this.domestic_inc_factor_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool domestic_inc_factor_next_daySpecified
        {
            get
            {
                return this.domestic_inc_factor_next_dayFieldSpecified;
            }
            set
            {
                this.domestic_inc_factor_next_dayFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal limited_investability_factor
        {
            get
            {
                return this.limited_investability_factorField;
            }
            set
            {
                this.limited_investability_factorField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool limited_investability_factorSpecified
        {
            get
            {
                return this.limited_investability_factorFieldSpecified;
            }
            set
            {
                this.limited_investability_factorFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal foreign_ownership_limit
        {
            get
            {
                return this.foreign_ownership_limitField;
            }
            set
            {
                this.foreign_ownership_limitField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool foreign_ownership_limitSpecified
        {
            get
            {
                return this.foreign_ownership_limitFieldSpecified;
            }
            set
            {
                this.foreign_ownership_limitFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal family_std_flag
        {
            get
            {
                return this.family_std_flagField;
            }
            set
            {
                this.family_std_flagField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool family_std_flagSpecified
        {
            get
            {
                return this.family_std_flagFieldSpecified;
            }
            set
            {
                this.family_std_flagFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal family_std_flag_next_day
        {
            get
            {
                return this.family_std_flag_next_dayField;
            }
            set
            {
                this.family_std_flag_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool family_std_flag_next_daySpecified
        {
            get
            {
                return this.family_std_flag_next_dayFieldSpecified;
            }
            set
            {
                this.family_std_flag_next_dayFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal family_std_dom_flag
        {
            get
            {
                return this.family_std_dom_flagField;
            }
            set
            {
                this.family_std_dom_flagField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool family_std_dom_flagSpecified
        {
            get
            {
                return this.family_std_dom_flagFieldSpecified;
            }
            set
            {
                this.family_std_dom_flagFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal family_std_dom_flag_next_day
        {
            get
            {
                return this.family_std_dom_flag_next_dayField;
            }
            set
            {
                this.family_std_dom_flag_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool family_std_dom_flag_next_daySpecified
        {
            get
            {
                return this.family_std_dom_flag_next_dayFieldSpecified;
            }
            set
            {
                this.family_std_dom_flag_next_dayFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal family_large_flag
        {
            get
            {
                return this.family_large_flagField;
            }
            set
            {
                this.family_large_flagField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool family_large_flagSpecified
        {
            get
            {
                return this.family_large_flagFieldSpecified;
            }
            set
            {
                this.family_large_flagFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal family_large_flag_next_day
        {
            get
            {
                return this.family_large_flag_next_dayField;
            }
            set
            {
                this.family_large_flag_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool family_large_flag_next_daySpecified
        {
            get
            {
                return this.family_large_flag_next_dayFieldSpecified;
            }
            set
            {
                this.family_large_flag_next_dayFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pro_forma_family_large_flag
        {
            get
            {
                return this.pro_forma_family_large_flagField;
            }
            set
            {
                this.pro_forma_family_large_flagField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pro_forma_family_large_flagSpecified
        {
            get
            {
                return this.pro_forma_family_large_flagFieldSpecified;
            }
            set
            {
                this.pro_forma_family_large_flagFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal family_mid_flag
        {
            get
            {
                return this.family_mid_flagField;
            }
            set
            {
                this.family_mid_flagField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool family_mid_flagSpecified
        {
            get
            {
                return this.family_mid_flagFieldSpecified;
            }
            set
            {
                this.family_mid_flagFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal family_mid_flag_next_day
        {
            get
            {
                return this.family_mid_flag_next_dayField;
            }
            set
            {
                this.family_mid_flag_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool family_mid_flag_next_daySpecified
        {
            get
            {
                return this.family_mid_flag_next_dayFieldSpecified;
            }
            set
            {
                this.family_mid_flag_next_dayFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pro_forma_family_mid_flag
        {
            get
            {
                return this.pro_forma_family_mid_flagField;
            }
            set
            {
                this.pro_forma_family_mid_flagField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pro_forma_family_mid_flagSpecified
        {
            get
            {
                return this.pro_forma_family_mid_flagFieldSpecified;
            }
            set
            {
                this.pro_forma_family_mid_flagFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ISO_country_symbol_next_day
        {
            get
            {
                return this.iSO_country_symbol_next_dayField;
            }
            set
            {
                this.iSO_country_symbol_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal value_of_quotation_next_day
        {
            get
            {
                return this.value_of_quotation_next_dayField;
            }
            set
            {
                this.value_of_quotation_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool value_of_quotation_next_daySpecified
        {
            get
            {
                return this.value_of_quotation_next_dayFieldSpecified;
            }
            set
            {
                this.value_of_quotation_next_dayFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pro_forma_FIF
        {
            get
            {
                return this.pro_forma_FIFField;
            }
            set
            {
                this.pro_forma_FIFField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pro_forma_FIFSpecified
        {
            get
            {
                return this.pro_forma_FIFFieldSpecified;
            }
            set
            {
                this.pro_forma_FIFFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pro_forma_DIF
        {
            get
            {
                return this.pro_forma_DIFField;
            }
            set
            {
                this.pro_forma_DIFField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pro_forma_DIFSpecified
        {
            get
            {
                return this.pro_forma_DIFFieldSpecified;
            }
            set
            {
                this.pro_forma_DIFFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pro_forma_family_std_flag
        {
            get
            {
                return this.pro_forma_family_std_flagField;
            }
            set
            {
                this.pro_forma_family_std_flagField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pro_forma_family_std_flagSpecified
        {
            get
            {
                return this.pro_forma_family_std_flagFieldSpecified;
            }
            set
            {
                this.pro_forma_family_std_flagFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pro_forma_family_std_dom_flag
        {
            get
            {
                return this.pro_forma_family_std_dom_flagField;
            }
            set
            {
                this.pro_forma_family_std_dom_flagField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pro_forma_family_std_dom_flagSpecified
        {
            get
            {
                return this.pro_forma_family_std_dom_flagFieldSpecified;
            }
            set
            {
                this.pro_forma_family_std_dom_flagFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal price_return_loc
        {
            get
            {
                return this.price_return_locField;
            }
            set
            {
                this.price_return_locField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool price_return_locSpecified
        {
            get
            {
                return this.price_return_locFieldSpecified;
            }
            set
            {
                this.price_return_locFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal price_return_usd
        {
            get
            {
                return this.price_return_usdField;
            }
            set
            {
                this.price_return_usdField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool price_return_usdSpecified
        {
            get
            {
                return this.price_return_usdFieldSpecified;
            }
            set
            {
                this.price_return_usdFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal gross_return_loc
        {
            get
            {
                return this.gross_return_locField;
            }
            set
            {
                this.gross_return_locField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gross_return_locSpecified
        {
            get
            {
                return this.gross_return_locFieldSpecified;
            }
            set
            {
                this.gross_return_locFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal gross_return_usd
        {
            get
            {
                return this.gross_return_usdField;
            }
            set
            {
                this.gross_return_usdField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gross_return_usdSpecified
        {
            get
            {
                return this.gross_return_usdFieldSpecified;
            }
            set
            {
                this.gross_return_usdFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal net_return_intl_loc
        {
            get
            {
                return this.net_return_intl_locField;
            }
            set
            {
                this.net_return_intl_locField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool net_return_intl_locSpecified
        {
            get
            {
                return this.net_return_intl_locFieldSpecified;
            }
            set
            {
                this.net_return_intl_locFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal net_return_intl_usd
        {
            get
            {
                return this.net_return_intl_usdField;
            }
            set
            {
                this.net_return_intl_usdField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool net_return_intl_usdSpecified
        {
            get
            {
                return this.net_return_intl_usdFieldSpecified;
            }
            set
            {
                this.net_return_intl_usdFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal initial_mkt_cap_usd
        {
            get
            {
                return this.initial_mkt_cap_usdField;
            }
            set
            {
                this.initial_mkt_cap_usdField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool initial_mkt_cap_usdSpecified
        {
            get
            {
                return this.initial_mkt_cap_usdFieldSpecified;
            }
            set
            {
                this.initial_mkt_cap_usdFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal initial_mkt_cap_usd_next_day
        {
            get
            {
                return this.initial_mkt_cap_usd_next_dayField;
            }
            set
            {
                this.initial_mkt_cap_usd_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool initial_mkt_cap_usd_next_daySpecified
        {
            get
            {
                return this.initial_mkt_cap_usd_next_dayFieldSpecified;
            }
            set
            {
                this.initial_mkt_cap_usd_next_dayFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal initial_mkt_cap_loc
        {
            get
            {
                return this.initial_mkt_cap_locField;
            }
            set
            {
                this.initial_mkt_cap_locField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool initial_mkt_cap_locSpecified
        {
            get
            {
                return this.initial_mkt_cap_locFieldSpecified;
            }
            set
            {
                this.initial_mkt_cap_locFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal initial_mkt_cap_loc_next_day
        {
            get
            {
                return this.initial_mkt_cap_loc_next_dayField;
            }
            set
            {
                this.initial_mkt_cap_loc_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool initial_mkt_cap_loc_next_daySpecified
        {
            get
            {
                return this.initial_mkt_cap_loc_next_dayFieldSpecified;
            }
            set
            {
                this.initial_mkt_cap_loc_next_dayFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal company_full_mktcap
        {
            get
            {
                return this.company_full_mktcapField;
            }
            set
            {
                this.company_full_mktcapField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool company_full_mktcapSpecified
        {
            get
            {
                return this.company_full_mktcapFieldSpecified;
            }
            set
            {
                this.company_full_mktcapFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal std_IIF
        {
            get
            {
                return this.std_IIFField;
            }
            set
            {
                this.std_IIFField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool std_IIFSpecified
        {
            get
            {
                return this.std_IIFFieldSpecified;
            }
            set
            {
                this.std_IIFFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal std_IIF_next_day
        {
            get
            {
                return this.std_IIF_next_dayField;
            }
            set
            {
                this.std_IIF_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool std_IIF_next_daySpecified
        {
            get
            {
                return this.std_IIF_next_dayFieldSpecified;
            }
            set
            {
                this.std_IIF_next_dayFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pro_forma_std_IIF
        {
            get
            {
                return this.pro_forma_std_IIFField;
            }
            set
            {
                this.pro_forma_std_IIFField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pro_forma_std_IIFSpecified
        {
            get
            {
                return this.pro_forma_std_IIFFieldSpecified;
            }
            set
            {
                this.pro_forma_std_IIFFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal family_large_dom_flag
        {
            get
            {
                return this.family_large_dom_flagField;
            }
            set
            {
                this.family_large_dom_flagField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool family_large_dom_flagSpecified
        {
            get
            {
                return this.family_large_dom_flagFieldSpecified;
            }
            set
            {
                this.family_large_dom_flagFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal family_large_dom_flag_next_day
        {
            get
            {
                return this.family_large_dom_flag_next_dayField;
            }
            set
            {
                this.family_large_dom_flag_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool family_large_dom_flag_next_daySpecified
        {
            get
            {
                return this.family_large_dom_flag_next_dayFieldSpecified;
            }
            set
            {
                this.family_large_dom_flag_next_dayFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pro_forma_family_large_dom_flg
        {
            get
            {
                return this.pro_forma_family_large_dom_flgField;
            }
            set
            {
                this.pro_forma_family_large_dom_flgField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pro_forma_family_large_dom_flgSpecified
        {
            get
            {
                return this.pro_forma_family_large_dom_flgFieldSpecified;
            }
            set
            {
                this.pro_forma_family_large_dom_flgFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pro_forma_sub_industry
        {
            get
            {
                return this.pro_forma_sub_industryField;
            }
            set
            {
                this.pro_forma_sub_industryField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pro_forma_sub_industrySpecified
        {
            get
            {
                return this.pro_forma_sub_industryFieldSpecified;
            }
            set
            {
                this.pro_forma_sub_industryFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pro_forma_eod_number_of_shares
        {
            get
            {
                return this.pro_forma_eod_number_of_sharesField;
            }
            set
            {
                this.pro_forma_eod_number_of_sharesField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pro_forma_eod_number_of_sharesSpecified
        {
            get
            {
                return this.pro_forma_eod_number_of_sharesFieldSpecified;
            }
            set
            {
                this.pro_forma_eod_number_of_sharesFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal family_mid_dom_flag
        {
            get
            {
                return this.family_mid_dom_flagField;
            }
            set
            {
                this.family_mid_dom_flagField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool family_mid_dom_flagSpecified
        {
            get
            {
                return this.family_mid_dom_flagFieldSpecified;
            }
            set
            {
                this.family_mid_dom_flagFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal family_mid_dom_flag_next_day
        {
            get
            {
                return this.family_mid_dom_flag_next_dayField;
            }
            set
            {
                this.family_mid_dom_flag_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool family_mid_dom_flag_next_daySpecified
        {
            get
            {
                return this.family_mid_dom_flag_next_dayFieldSpecified;
            }
            set
            {
                this.family_mid_dom_flag_next_dayFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal pro_forma_family_mid_dom_flg
        {
            get
            {
                return this.pro_forma_family_mid_dom_flgField;
            }
            set
            {
                this.pro_forma_family_mid_dom_flgField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pro_forma_family_mid_dom_flgSpecified
        {
            get
            {
                return this.pro_forma_family_mid_dom_flgFieldSpecified;
            }
            set
            {
                this.pro_forma_family_mid_dom_flgFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal unadj_market_cap_today_usdol
        {
            get
            {
                return this.unadj_market_cap_today_usdolField;
            }
            set
            {
                this.unadj_market_cap_today_usdolField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unadj_market_cap_today_usdolSpecified
        {
            get
            {
                return this.unadj_market_cap_today_usdolFieldSpecified;
            }
            set
            {
                this.unadj_market_cap_today_usdolFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal adj_market_cap_usdol
        {
            get
            {
                return this.adj_market_cap_usdolField;
            }
            set
            {
                this.adj_market_cap_usdolField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adj_market_cap_usdolSpecified
        {
            get
            {
                return this.adj_market_cap_usdolFieldSpecified;
            }
            set
            {
                this.adj_market_cap_usdolFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal fm_universe_flag
        {
            get
            {
                return this.fm_universe_flagField;
            }
            set
            {
                this.fm_universe_flagField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fm_universe_flagSpecified
        {
            get
            {
                return this.fm_universe_flagFieldSpecified;
            }
            set
            {
                this.fm_universe_flagFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal gcc_universe_flag
        {
            get
            {
                return this.gcc_universe_flagField;
            }
            set
            {
                this.gcc_universe_flagField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gcc_universe_flagSpecified
        {
            get
            {
                return this.gcc_universe_flagFieldSpecified;
            }
            set
            {
                this.gcc_universe_flagFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RIC
        {
            get
            {
                return this.rICField;
            }
            set
            {
                this.rICField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bb_ticker
        {
            get
            {
                return this.bb_tickerField;
            }
            set
            {
                this.bb_tickerField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sedol_next_day
        {
            get
            {
                return this.sedol_next_dayField;
            }
            set
            {
                this.sedol_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string share_class
        {
            get
            {
                return this.share_classField;
            }
            set
            {
                this.share_classField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string share_type
        {
            get
            {
                return this.share_typeField;
            }
            set
            {
                this.share_typeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string alternate_listing
        {
            get
            {
                return this.alternate_listingField;
            }
            set
            {
                this.alternate_listingField = value;
            }
        }
    }
}
