// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>MSCIBarra_EquityIndex</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MSCIBarra_EquityIndex {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.mscibarra.com/ns/msci/deal/D51D")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://xml.mscibarra.com/ns/msci/deal/D51D", IsNullable=false)]
    public partial class package_D51D {
        
        private List<package_D51DEntry> dataset_D51DField;
        
        public package_D51D() {
            this.dataset_D51DField = new List<package_D51DEntry>();
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
        public List<package_D51DEntry> dataset_D51D {
            get {
                return this.dataset_D51DField;
            }
            set {
                this.dataset_D51DField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.mscibarra.com/ns/msci/deal/D51D")]
    public partial class package_D51DEntry {
        
        private System.DateTime calc_dateField;
        
        private decimal msci_index_codeField;
        
        private string index_nameField;
        
        private string real_time_ricField;
        
        private string real_time_tickerField;
        
        private string iSO_country_symbolField;
        
        private string region_codeField;
        
        private decimal dM_flagField;
        
        private decimal eM_flagField;
        
        private decimal aP_flagField;
        
        private bool aP_flagFieldSpecified;
        
        private decimal value_flagField;
        
        private bool value_flagFieldSpecified;
        
        private decimal growth_flagField;
        
        private bool growth_flagFieldSpecified;
        
        private decimal small_cap_flagField;
        
        private bool small_cap_flagFieldSpecified;
        
        private decimal mid_cap_flagField;
        
        private bool mid_cap_flagFieldSpecified;
        
        private decimal large_cap_flagField;
        
        private bool large_cap_flagFieldSpecified;
        
        private decimal micro_cap_flagField;
        
        private bool micro_cap_flagFieldSpecified;
        
        private decimal islamic_index_flagField;
        
        private bool islamic_index_flagFieldSpecified;
        
        private decimal sectorField;
        
        private bool sectorFieldSpecified;
        
        private decimal industry_groupField;
        
        private bool industry_groupFieldSpecified;
        
        private decimal industryField;
        
        private bool industryFieldSpecified;
        
        private decimal sub_industryField;
        
        private bool sub_industryFieldSpecified;
        
        private decimal count_of_securitiesField;
        
        private decimal unadj_mkt_cap_eod00d_usdField;
        
        private bool unadj_mkt_cap_eod00d_usdFieldSpecified;
        
        private System.DateTime std_latest_index_base_dateField;
        
        private bool std_latest_index_base_dateFieldSpecified;
        
        private System.DateTime grs_latest_index_base_dateField;
        
        private bool grs_latest_index_base_dateFieldSpecified;
        
        private System.DateTime net_latest_index_base_dateField;
        
        private bool net_latest_index_base_dateFieldSpecified;
        
        private string std_variant_typeField;
        
        private decimal std_eod00d_usdField;
        
        private bool std_eod00d_usdFieldSpecified;
        
        private decimal std_eod00d_localField;
        
        private bool std_eod00d_localFieldSpecified;
        
        private string grs_variant_typeField;
        
        private decimal grs_eod00d_usdField;
        
        private bool grs_eod00d_usdFieldSpecified;
        
        private decimal grs_eod00d_localField;
        
        private bool grs_eod00d_localFieldSpecified;
        
        private string net_variant_typeField;
        
        private decimal net_eod00d_usdField;
        
        private bool net_eod00d_usdFieldSpecified;
        
        private decimal net_eod00d_localField;
        
        private bool net_eod00d_localFieldSpecified;
        
        private decimal daily_yieldField;
        
        private bool daily_yieldFieldSpecified;
        
        private decimal adj_mkt_cap_eod00d_usdField;
        
        private bool adj_mkt_cap_eod00d_usdFieldSpecified;
        
        private decimal initial_mkt_cap_eod00d_usdField;
        
        private bool initial_mkt_cap_eod00d_usdFieldSpecified;
        
        private decimal initial_mkt_cap_eod00d_usd_ndField;
        
        private bool initial_mkt_cap_eod00d_usd_ndFieldSpecified;
        
        private decimal full_issuer_mkt_cap_cutoff_usdField;
        
        private bool full_issuer_mkt_cap_cutoff_usdFieldSpecified;
        
        private string mkt_cap_ISO_symbol_ccyField;
        
        private decimal unadj_mkt_cap_eod00d_curField;
        
        private bool unadj_mkt_cap_eod00d_curFieldSpecified;
        
        private decimal gmsr_usdField;
        
        private bool gmsr_usdFieldSpecified;
        
        private decimal target_nb_companiesField;
        
        private bool target_nb_companiesFieldSpecified;
        
        private decimal std_index_base_valueField;
        
        private bool std_index_base_valueFieldSpecified;
        
        private decimal grs_index_base_valueField;
        
        private bool grs_index_base_valueFieldSpecified;
        
        private decimal net_index_base_valueField;
        
        private bool net_index_base_valueFieldSpecified;
        
        private decimal std_index_divisor_usdField;
        
        private bool std_index_divisor_usdFieldSpecified;
        
        private decimal std_index_divisor_usd_ndField;
        
        private bool std_index_divisor_usd_ndFieldSpecified;
        
        private decimal grs_index_divisor_usdField;
        
        private bool grs_index_divisor_usdFieldSpecified;
        
        private decimal grs_index_divisor_usd_ndField;
        
        private bool grs_index_divisor_usd_ndFieldSpecified;
        
        private decimal net_index_divisor_usdField;
        
        private bool net_index_divisor_usdFieldSpecified;
        
        private decimal net_index_divisor_usd_ndField;
        
        private bool net_index_divisor_usd_ndFieldSpecified;
        
        private decimal std_idx_div_pts_grs_usdField;
        
        private bool std_idx_div_pts_grs_usdFieldSpecified;
        
        private decimal std_idx_div_pts_grs_usd_prelimField;
        
        private bool std_idx_div_pts_grs_usd_prelimFieldSpecified;
        
        private decimal std_idx_div_pts_net_usdField;
        
        private bool std_idx_div_pts_net_usdFieldSpecified;
        
        private decimal std_idx_div_pts_net_usd_prelimField;
        
        private bool std_idx_div_pts_net_usd_prelimFieldSpecified;
        
        private decimal grs_idx_div_pts_grs_usdField;
        
        private bool grs_idx_div_pts_grs_usdFieldSpecified;
        
        private decimal grs_idx_div_pts_grs_usd_prelimField;
        
        private bool grs_idx_div_pts_grs_usd_prelimFieldSpecified;
        
        private decimal net_idx_div_pts_net_usdField;
        
        private bool net_idx_div_pts_net_usdFieldSpecified;
        
        private decimal net_idx_div_pts_net_usd_prelimField;
        
        private bool net_idx_div_pts_net_usd_prelimFieldSpecified;
        
        private decimal std_since_high_usdField;
        
        private bool std_since_high_usdFieldSpecified;
        
        private decimal std_since_high_localField;
        
        private bool std_since_high_localFieldSpecified;
        
        private decimal std_since_low_usdField;
        
        private bool std_since_low_usdFieldSpecified;
        
        private decimal std_since_low_localField;
        
        private bool std_since_low_localFieldSpecified;
        
        private decimal grs_since_high_usdField;
        
        private bool grs_since_high_usdFieldSpecified;
        
        private decimal grs_since_high_localField;
        
        private bool grs_since_high_localFieldSpecified;
        
        private decimal grs_since_low_usdField;
        
        private bool grs_since_low_usdFieldSpecified;
        
        private decimal grs_since_low_localField;
        
        private bool grs_since_low_localFieldSpecified;
        
        private decimal net_since_high_usdField;
        
        private bool net_since_high_usdFieldSpecified;
        
        private decimal net_since_high_localField;
        
        private bool net_since_high_localFieldSpecified;
        
        private decimal net_since_low_usdField;
        
        private bool net_since_low_usdFieldSpecified;
        
        private decimal net_since_low_localField;
        
        private bool net_since_low_localFieldSpecified;
        
        private string hdg_variant_typeField;
        
        private decimal hdg_eom00m_usdField;
        
        private bool hdg_eom00m_usdFieldSpecified;
        
        private decimal price_to_book_valueField;
        
        private bool price_to_book_valueFieldSpecified;
        
        private decimal price_to_cash_earningsField;
        
        private bool price_to_cash_earningsFieldSpecified;
        
        private decimal price_to_earningsField;
        
        private bool price_to_earningsFieldSpecified;
        
        private decimal yieldField;
        
        private bool yieldFieldSpecified;
        
        private decimal roeField;
        
        private bool roeFieldSpecified;
        
        private decimal bwd_price_to_earnField;
        
        private bool bwd_price_to_earnFieldSpecified;
        
        private decimal lt_fwd_earn_per_share_gField;
        
        private bool lt_fwd_earn_per_share_gFieldSpecified;
        
        private decimal st_fwd_earn_per_share_gField;
        
        private bool st_fwd_earn_per_share_gFieldSpecified;
        
        private decimal fwd_price_to_earnField;
        
        private bool fwd_price_to_earnFieldSpecified;
        
        private decimal curr_internal_growth_rateField;
        
        private bool curr_internal_growth_rateFieldSpecified;
        
        private decimal lt_hist_eps_gField;
        
        private bool lt_hist_eps_gFieldSpecified;
        
        private decimal lt_hist_sps_gField;
        
        private bool lt_hist_sps_gFieldSpecified;
        
        private decimal _12m_trailing_epsField;
        
        private bool _12m_trailing_epsFieldSpecified;
        
        private decimal _12m_forward_epsField;
        
        private bool _12m_forward_epsFieldSpecified;
        
        private decimal y_on_y_growth_trailing_epsField;
        
        private bool y_on_y_growth_trailing_epsFieldSpecified;
        
        private decimal y_on_y_growth_forward_epsField;
        
        private bool y_on_y_growth_forward_epsFieldSpecified;
        
        private decimal average_mktcapField;
        
        private bool average_mktcapFieldSpecified;
        
        private decimal median_mktcapField;
        
        private bool median_mktcapFieldSpecified;
        
        private decimal _5_years_ADPS_growth_rateField;
        
        private bool _5_years_ADPS_growth_rateFieldSpecified;
        
        private decimal _1_year_ADPS_growth_rateField;
        
        private bool _1_year_ADPS_growth_rateFieldSpecified;
        
        private decimal payout_ratioField;
        
        private bool payout_ratioFieldSpecified;
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime calc_date {
            get {
                return this.calc_dateField;
            }
            set {
                this.calc_dateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal msci_index_code {
            get {
                return this.msci_index_codeField;
            }
            set {
                this.msci_index_codeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index_name {
            get {
                return this.index_nameField;
            }
            set {
                this.index_nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string real_time_ric {
            get {
                return this.real_time_ricField;
            }
            set {
                this.real_time_ricField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string real_time_ticker {
            get {
                return this.real_time_tickerField;
            }
            set {
                this.real_time_tickerField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ISO_country_symbol {
            get {
                return this.iSO_country_symbolField;
            }
            set {
                this.iSO_country_symbolField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string region_code {
            get {
                return this.region_codeField;
            }
            set {
                this.region_codeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal DM_flag {
            get {
                return this.dM_flagField;
            }
            set {
                this.dM_flagField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal EM_flag {
            get {
                return this.eM_flagField;
            }
            set {
                this.eM_flagField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal AP_flag {
            get {
                return this.aP_flagField;
            }
            set {
                this.aP_flagField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AP_flagSpecified {
            get {
                return this.aP_flagFieldSpecified;
            }
            set {
                this.aP_flagFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal value_flag {
            get {
                return this.value_flagField;
            }
            set {
                this.value_flagField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool value_flagSpecified {
            get {
                return this.value_flagFieldSpecified;
            }
            set {
                this.value_flagFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal growth_flag {
            get {
                return this.growth_flagField;
            }
            set {
                this.growth_flagField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool growth_flagSpecified {
            get {
                return this.growth_flagFieldSpecified;
            }
            set {
                this.growth_flagFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal small_cap_flag {
            get {
                return this.small_cap_flagField;
            }
            set {
                this.small_cap_flagField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool small_cap_flagSpecified {
            get {
                return this.small_cap_flagFieldSpecified;
            }
            set {
                this.small_cap_flagFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal mid_cap_flag {
            get {
                return this.mid_cap_flagField;
            }
            set {
                this.mid_cap_flagField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mid_cap_flagSpecified {
            get {
                return this.mid_cap_flagFieldSpecified;
            }
            set {
                this.mid_cap_flagFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal large_cap_flag {
            get {
                return this.large_cap_flagField;
            }
            set {
                this.large_cap_flagField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool large_cap_flagSpecified {
            get {
                return this.large_cap_flagFieldSpecified;
            }
            set {
                this.large_cap_flagFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal micro_cap_flag {
            get {
                return this.micro_cap_flagField;
            }
            set {
                this.micro_cap_flagField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool micro_cap_flagSpecified {
            get {
                return this.micro_cap_flagFieldSpecified;
            }
            set {
                this.micro_cap_flagFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal islamic_index_flag {
            get {
                return this.islamic_index_flagField;
            }
            set {
                this.islamic_index_flagField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool islamic_index_flagSpecified {
            get {
                return this.islamic_index_flagFieldSpecified;
            }
            set {
                this.islamic_index_flagFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal sector {
            get {
                return this.sectorField;
            }
            set {
                this.sectorField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sectorSpecified {
            get {
                return this.sectorFieldSpecified;
            }
            set {
                this.sectorFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal industry_group {
            get {
                return this.industry_groupField;
            }
            set {
                this.industry_groupField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool industry_groupSpecified {
            get {
                return this.industry_groupFieldSpecified;
            }
            set {
                this.industry_groupFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal industry {
            get {
                return this.industryField;
            }
            set {
                this.industryField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool industrySpecified {
            get {
                return this.industryFieldSpecified;
            }
            set {
                this.industryFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal sub_industry {
            get {
                return this.sub_industryField;
            }
            set {
                this.sub_industryField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sub_industrySpecified {
            get {
                return this.sub_industryFieldSpecified;
            }
            set {
                this.sub_industryFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal count_of_securities {
            get {
                return this.count_of_securitiesField;
            }
            set {
                this.count_of_securitiesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal unadj_mkt_cap_eod00d_usd {
            get {
                return this.unadj_mkt_cap_eod00d_usdField;
            }
            set {
                this.unadj_mkt_cap_eod00d_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unadj_mkt_cap_eod00d_usdSpecified {
            get {
                return this.unadj_mkt_cap_eod00d_usdFieldSpecified;
            }
            set {
                this.unadj_mkt_cap_eod00d_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime std_latest_index_base_date {
            get {
                return this.std_latest_index_base_dateField;
            }
            set {
                this.std_latest_index_base_dateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool std_latest_index_base_dateSpecified {
            get {
                return this.std_latest_index_base_dateFieldSpecified;
            }
            set {
                this.std_latest_index_base_dateFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime grs_latest_index_base_date {
            get {
                return this.grs_latest_index_base_dateField;
            }
            set {
                this.grs_latest_index_base_dateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grs_latest_index_base_dateSpecified {
            get {
                return this.grs_latest_index_base_dateFieldSpecified;
            }
            set {
                this.grs_latest_index_base_dateFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime net_latest_index_base_date {
            get {
                return this.net_latest_index_base_dateField;
            }
            set {
                this.net_latest_index_base_dateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool net_latest_index_base_dateSpecified {
            get {
                return this.net_latest_index_base_dateFieldSpecified;
            }
            set {
                this.net_latest_index_base_dateFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string std_variant_type {
            get {
                return this.std_variant_typeField;
            }
            set {
                this.std_variant_typeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal std_eod00d_usd {
            get {
                return this.std_eod00d_usdField;
            }
            set {
                this.std_eod00d_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool std_eod00d_usdSpecified {
            get {
                return this.std_eod00d_usdFieldSpecified;
            }
            set {
                this.std_eod00d_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal std_eod00d_local {
            get {
                return this.std_eod00d_localField;
            }
            set {
                this.std_eod00d_localField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool std_eod00d_localSpecified {
            get {
                return this.std_eod00d_localFieldSpecified;
            }
            set {
                this.std_eod00d_localFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string grs_variant_type {
            get {
                return this.grs_variant_typeField;
            }
            set {
                this.grs_variant_typeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal grs_eod00d_usd {
            get {
                return this.grs_eod00d_usdField;
            }
            set {
                this.grs_eod00d_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grs_eod00d_usdSpecified {
            get {
                return this.grs_eod00d_usdFieldSpecified;
            }
            set {
                this.grs_eod00d_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal grs_eod00d_local {
            get {
                return this.grs_eod00d_localField;
            }
            set {
                this.grs_eod00d_localField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grs_eod00d_localSpecified {
            get {
                return this.grs_eod00d_localFieldSpecified;
            }
            set {
                this.grs_eod00d_localFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string net_variant_type {
            get {
                return this.net_variant_typeField;
            }
            set {
                this.net_variant_typeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal net_eod00d_usd {
            get {
                return this.net_eod00d_usdField;
            }
            set {
                this.net_eod00d_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool net_eod00d_usdSpecified {
            get {
                return this.net_eod00d_usdFieldSpecified;
            }
            set {
                this.net_eod00d_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal net_eod00d_local {
            get {
                return this.net_eod00d_localField;
            }
            set {
                this.net_eod00d_localField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool net_eod00d_localSpecified {
            get {
                return this.net_eod00d_localFieldSpecified;
            }
            set {
                this.net_eod00d_localFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal daily_yield {
            get {
                return this.daily_yieldField;
            }
            set {
                this.daily_yieldField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool daily_yieldSpecified {
            get {
                return this.daily_yieldFieldSpecified;
            }
            set {
                this.daily_yieldFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal adj_mkt_cap_eod00d_usd {
            get {
                return this.adj_mkt_cap_eod00d_usdField;
            }
            set {
                this.adj_mkt_cap_eod00d_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adj_mkt_cap_eod00d_usdSpecified {
            get {
                return this.adj_mkt_cap_eod00d_usdFieldSpecified;
            }
            set {
                this.adj_mkt_cap_eod00d_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal initial_mkt_cap_eod00d_usd {
            get {
                return this.initial_mkt_cap_eod00d_usdField;
            }
            set {
                this.initial_mkt_cap_eod00d_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool initial_mkt_cap_eod00d_usdSpecified {
            get {
                return this.initial_mkt_cap_eod00d_usdFieldSpecified;
            }
            set {
                this.initial_mkt_cap_eod00d_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal initial_mkt_cap_eod00d_usd_nd {
            get {
                return this.initial_mkt_cap_eod00d_usd_ndField;
            }
            set {
                this.initial_mkt_cap_eod00d_usd_ndField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool initial_mkt_cap_eod00d_usd_ndSpecified {
            get {
                return this.initial_mkt_cap_eod00d_usd_ndFieldSpecified;
            }
            set {
                this.initial_mkt_cap_eod00d_usd_ndFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal full_issuer_mkt_cap_cutoff_usd {
            get {
                return this.full_issuer_mkt_cap_cutoff_usdField;
            }
            set {
                this.full_issuer_mkt_cap_cutoff_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool full_issuer_mkt_cap_cutoff_usdSpecified {
            get {
                return this.full_issuer_mkt_cap_cutoff_usdFieldSpecified;
            }
            set {
                this.full_issuer_mkt_cap_cutoff_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mkt_cap_ISO_symbol_ccy {
            get {
                return this.mkt_cap_ISO_symbol_ccyField;
            }
            set {
                this.mkt_cap_ISO_symbol_ccyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal unadj_mkt_cap_eod00d_cur {
            get {
                return this.unadj_mkt_cap_eod00d_curField;
            }
            set {
                this.unadj_mkt_cap_eod00d_curField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unadj_mkt_cap_eod00d_curSpecified {
            get {
                return this.unadj_mkt_cap_eod00d_curFieldSpecified;
            }
            set {
                this.unadj_mkt_cap_eod00d_curFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal gmsr_usd {
            get {
                return this.gmsr_usdField;
            }
            set {
                this.gmsr_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gmsr_usdSpecified {
            get {
                return this.gmsr_usdFieldSpecified;
            }
            set {
                this.gmsr_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal target_nb_companies {
            get {
                return this.target_nb_companiesField;
            }
            set {
                this.target_nb_companiesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool target_nb_companiesSpecified {
            get {
                return this.target_nb_companiesFieldSpecified;
            }
            set {
                this.target_nb_companiesFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal std_index_base_value {
            get {
                return this.std_index_base_valueField;
            }
            set {
                this.std_index_base_valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool std_index_base_valueSpecified {
            get {
                return this.std_index_base_valueFieldSpecified;
            }
            set {
                this.std_index_base_valueFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal grs_index_base_value {
            get {
                return this.grs_index_base_valueField;
            }
            set {
                this.grs_index_base_valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grs_index_base_valueSpecified {
            get {
                return this.grs_index_base_valueFieldSpecified;
            }
            set {
                this.grs_index_base_valueFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal net_index_base_value {
            get {
                return this.net_index_base_valueField;
            }
            set {
                this.net_index_base_valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool net_index_base_valueSpecified {
            get {
                return this.net_index_base_valueFieldSpecified;
            }
            set {
                this.net_index_base_valueFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal std_index_divisor_usd {
            get {
                return this.std_index_divisor_usdField;
            }
            set {
                this.std_index_divisor_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool std_index_divisor_usdSpecified {
            get {
                return this.std_index_divisor_usdFieldSpecified;
            }
            set {
                this.std_index_divisor_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal std_index_divisor_usd_nd {
            get {
                return this.std_index_divisor_usd_ndField;
            }
            set {
                this.std_index_divisor_usd_ndField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool std_index_divisor_usd_ndSpecified {
            get {
                return this.std_index_divisor_usd_ndFieldSpecified;
            }
            set {
                this.std_index_divisor_usd_ndFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal grs_index_divisor_usd {
            get {
                return this.grs_index_divisor_usdField;
            }
            set {
                this.grs_index_divisor_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grs_index_divisor_usdSpecified {
            get {
                return this.grs_index_divisor_usdFieldSpecified;
            }
            set {
                this.grs_index_divisor_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal grs_index_divisor_usd_nd {
            get {
                return this.grs_index_divisor_usd_ndField;
            }
            set {
                this.grs_index_divisor_usd_ndField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grs_index_divisor_usd_ndSpecified {
            get {
                return this.grs_index_divisor_usd_ndFieldSpecified;
            }
            set {
                this.grs_index_divisor_usd_ndFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal net_index_divisor_usd {
            get {
                return this.net_index_divisor_usdField;
            }
            set {
                this.net_index_divisor_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool net_index_divisor_usdSpecified {
            get {
                return this.net_index_divisor_usdFieldSpecified;
            }
            set {
                this.net_index_divisor_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal net_index_divisor_usd_nd {
            get {
                return this.net_index_divisor_usd_ndField;
            }
            set {
                this.net_index_divisor_usd_ndField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool net_index_divisor_usd_ndSpecified {
            get {
                return this.net_index_divisor_usd_ndFieldSpecified;
            }
            set {
                this.net_index_divisor_usd_ndFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal std_idx_div_pts_grs_usd {
            get {
                return this.std_idx_div_pts_grs_usdField;
            }
            set {
                this.std_idx_div_pts_grs_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool std_idx_div_pts_grs_usdSpecified {
            get {
                return this.std_idx_div_pts_grs_usdFieldSpecified;
            }
            set {
                this.std_idx_div_pts_grs_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal std_idx_div_pts_grs_usd_prelim {
            get {
                return this.std_idx_div_pts_grs_usd_prelimField;
            }
            set {
                this.std_idx_div_pts_grs_usd_prelimField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool std_idx_div_pts_grs_usd_prelimSpecified {
            get {
                return this.std_idx_div_pts_grs_usd_prelimFieldSpecified;
            }
            set {
                this.std_idx_div_pts_grs_usd_prelimFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal std_idx_div_pts_net_usd {
            get {
                return this.std_idx_div_pts_net_usdField;
            }
            set {
                this.std_idx_div_pts_net_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool std_idx_div_pts_net_usdSpecified {
            get {
                return this.std_idx_div_pts_net_usdFieldSpecified;
            }
            set {
                this.std_idx_div_pts_net_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal std_idx_div_pts_net_usd_prelim {
            get {
                return this.std_idx_div_pts_net_usd_prelimField;
            }
            set {
                this.std_idx_div_pts_net_usd_prelimField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool std_idx_div_pts_net_usd_prelimSpecified {
            get {
                return this.std_idx_div_pts_net_usd_prelimFieldSpecified;
            }
            set {
                this.std_idx_div_pts_net_usd_prelimFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal grs_idx_div_pts_grs_usd {
            get {
                return this.grs_idx_div_pts_grs_usdField;
            }
            set {
                this.grs_idx_div_pts_grs_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grs_idx_div_pts_grs_usdSpecified {
            get {
                return this.grs_idx_div_pts_grs_usdFieldSpecified;
            }
            set {
                this.grs_idx_div_pts_grs_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal grs_idx_div_pts_grs_usd_prelim {
            get {
                return this.grs_idx_div_pts_grs_usd_prelimField;
            }
            set {
                this.grs_idx_div_pts_grs_usd_prelimField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grs_idx_div_pts_grs_usd_prelimSpecified {
            get {
                return this.grs_idx_div_pts_grs_usd_prelimFieldSpecified;
            }
            set {
                this.grs_idx_div_pts_grs_usd_prelimFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal net_idx_div_pts_net_usd {
            get {
                return this.net_idx_div_pts_net_usdField;
            }
            set {
                this.net_idx_div_pts_net_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool net_idx_div_pts_net_usdSpecified {
            get {
                return this.net_idx_div_pts_net_usdFieldSpecified;
            }
            set {
                this.net_idx_div_pts_net_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal net_idx_div_pts_net_usd_prelim {
            get {
                return this.net_idx_div_pts_net_usd_prelimField;
            }
            set {
                this.net_idx_div_pts_net_usd_prelimField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool net_idx_div_pts_net_usd_prelimSpecified {
            get {
                return this.net_idx_div_pts_net_usd_prelimFieldSpecified;
            }
            set {
                this.net_idx_div_pts_net_usd_prelimFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal std_since_high_usd {
            get {
                return this.std_since_high_usdField;
            }
            set {
                this.std_since_high_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool std_since_high_usdSpecified {
            get {
                return this.std_since_high_usdFieldSpecified;
            }
            set {
                this.std_since_high_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal std_since_high_local {
            get {
                return this.std_since_high_localField;
            }
            set {
                this.std_since_high_localField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool std_since_high_localSpecified {
            get {
                return this.std_since_high_localFieldSpecified;
            }
            set {
                this.std_since_high_localFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal std_since_low_usd {
            get {
                return this.std_since_low_usdField;
            }
            set {
                this.std_since_low_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool std_since_low_usdSpecified {
            get {
                return this.std_since_low_usdFieldSpecified;
            }
            set {
                this.std_since_low_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal std_since_low_local {
            get {
                return this.std_since_low_localField;
            }
            set {
                this.std_since_low_localField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool std_since_low_localSpecified {
            get {
                return this.std_since_low_localFieldSpecified;
            }
            set {
                this.std_since_low_localFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal grs_since_high_usd {
            get {
                return this.grs_since_high_usdField;
            }
            set {
                this.grs_since_high_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grs_since_high_usdSpecified {
            get {
                return this.grs_since_high_usdFieldSpecified;
            }
            set {
                this.grs_since_high_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal grs_since_high_local {
            get {
                return this.grs_since_high_localField;
            }
            set {
                this.grs_since_high_localField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grs_since_high_localSpecified {
            get {
                return this.grs_since_high_localFieldSpecified;
            }
            set {
                this.grs_since_high_localFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal grs_since_low_usd {
            get {
                return this.grs_since_low_usdField;
            }
            set {
                this.grs_since_low_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grs_since_low_usdSpecified {
            get {
                return this.grs_since_low_usdFieldSpecified;
            }
            set {
                this.grs_since_low_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal grs_since_low_local {
            get {
                return this.grs_since_low_localField;
            }
            set {
                this.grs_since_low_localField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool grs_since_low_localSpecified {
            get {
                return this.grs_since_low_localFieldSpecified;
            }
            set {
                this.grs_since_low_localFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal net_since_high_usd {
            get {
                return this.net_since_high_usdField;
            }
            set {
                this.net_since_high_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool net_since_high_usdSpecified {
            get {
                return this.net_since_high_usdFieldSpecified;
            }
            set {
                this.net_since_high_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal net_since_high_local {
            get {
                return this.net_since_high_localField;
            }
            set {
                this.net_since_high_localField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool net_since_high_localSpecified {
            get {
                return this.net_since_high_localFieldSpecified;
            }
            set {
                this.net_since_high_localFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal net_since_low_usd {
            get {
                return this.net_since_low_usdField;
            }
            set {
                this.net_since_low_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool net_since_low_usdSpecified {
            get {
                return this.net_since_low_usdFieldSpecified;
            }
            set {
                this.net_since_low_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal net_since_low_local {
            get {
                return this.net_since_low_localField;
            }
            set {
                this.net_since_low_localField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool net_since_low_localSpecified {
            get {
                return this.net_since_low_localFieldSpecified;
            }
            set {
                this.net_since_low_localFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string hdg_variant_type {
            get {
                return this.hdg_variant_typeField;
            }
            set {
                this.hdg_variant_typeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal hdg_eom00m_usd {
            get {
                return this.hdg_eom00m_usdField;
            }
            set {
                this.hdg_eom00m_usdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hdg_eom00m_usdSpecified {
            get {
                return this.hdg_eom00m_usdFieldSpecified;
            }
            set {
                this.hdg_eom00m_usdFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal price_to_book_value {
            get {
                return this.price_to_book_valueField;
            }
            set {
                this.price_to_book_valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool price_to_book_valueSpecified {
            get {
                return this.price_to_book_valueFieldSpecified;
            }
            set {
                this.price_to_book_valueFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal price_to_cash_earnings {
            get {
                return this.price_to_cash_earningsField;
            }
            set {
                this.price_to_cash_earningsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool price_to_cash_earningsSpecified {
            get {
                return this.price_to_cash_earningsFieldSpecified;
            }
            set {
                this.price_to_cash_earningsFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal price_to_earnings {
            get {
                return this.price_to_earningsField;
            }
            set {
                this.price_to_earningsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool price_to_earningsSpecified {
            get {
                return this.price_to_earningsFieldSpecified;
            }
            set {
                this.price_to_earningsFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal yield {
            get {
                return this.yieldField;
            }
            set {
                this.yieldField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yieldSpecified {
            get {
                return this.yieldFieldSpecified;
            }
            set {
                this.yieldFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal roe {
            get {
                return this.roeField;
            }
            set {
                this.roeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool roeSpecified {
            get {
                return this.roeFieldSpecified;
            }
            set {
                this.roeFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal bwd_price_to_earn {
            get {
                return this.bwd_price_to_earnField;
            }
            set {
                this.bwd_price_to_earnField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bwd_price_to_earnSpecified {
            get {
                return this.bwd_price_to_earnFieldSpecified;
            }
            set {
                this.bwd_price_to_earnFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lt_fwd_earn_per_share_g {
            get {
                return this.lt_fwd_earn_per_share_gField;
            }
            set {
                this.lt_fwd_earn_per_share_gField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lt_fwd_earn_per_share_gSpecified {
            get {
                return this.lt_fwd_earn_per_share_gFieldSpecified;
            }
            set {
                this.lt_fwd_earn_per_share_gFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal st_fwd_earn_per_share_g {
            get {
                return this.st_fwd_earn_per_share_gField;
            }
            set {
                this.st_fwd_earn_per_share_gField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool st_fwd_earn_per_share_gSpecified {
            get {
                return this.st_fwd_earn_per_share_gFieldSpecified;
            }
            set {
                this.st_fwd_earn_per_share_gFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal fwd_price_to_earn {
            get {
                return this.fwd_price_to_earnField;
            }
            set {
                this.fwd_price_to_earnField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fwd_price_to_earnSpecified {
            get {
                return this.fwd_price_to_earnFieldSpecified;
            }
            set {
                this.fwd_price_to_earnFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal curr_internal_growth_rate {
            get {
                return this.curr_internal_growth_rateField;
            }
            set {
                this.curr_internal_growth_rateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool curr_internal_growth_rateSpecified {
            get {
                return this.curr_internal_growth_rateFieldSpecified;
            }
            set {
                this.curr_internal_growth_rateFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lt_hist_eps_g {
            get {
                return this.lt_hist_eps_gField;
            }
            set {
                this.lt_hist_eps_gField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lt_hist_eps_gSpecified {
            get {
                return this.lt_hist_eps_gFieldSpecified;
            }
            set {
                this.lt_hist_eps_gFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal lt_hist_sps_g {
            get {
                return this.lt_hist_sps_gField;
            }
            set {
                this.lt_hist_sps_gField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lt_hist_sps_gSpecified {
            get {
                return this.lt_hist_sps_gFieldSpecified;
            }
            set {
                this.lt_hist_sps_gFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal _12m_trailing_eps {
            get {
                return this._12m_trailing_epsField;
            }
            set {
                this._12m_trailing_epsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool _12m_trailing_epsSpecified {
            get {
                return this._12m_trailing_epsFieldSpecified;
            }
            set {
                this._12m_trailing_epsFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal _12m_forward_eps {
            get {
                return this._12m_forward_epsField;
            }
            set {
                this._12m_forward_epsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool _12m_forward_epsSpecified {
            get {
                return this._12m_forward_epsFieldSpecified;
            }
            set {
                this._12m_forward_epsFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal y_on_y_growth_trailing_eps {
            get {
                return this.y_on_y_growth_trailing_epsField;
            }
            set {
                this.y_on_y_growth_trailing_epsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool y_on_y_growth_trailing_epsSpecified {
            get {
                return this.y_on_y_growth_trailing_epsFieldSpecified;
            }
            set {
                this.y_on_y_growth_trailing_epsFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal y_on_y_growth_forward_eps {
            get {
                return this.y_on_y_growth_forward_epsField;
            }
            set {
                this.y_on_y_growth_forward_epsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool y_on_y_growth_forward_epsSpecified {
            get {
                return this.y_on_y_growth_forward_epsFieldSpecified;
            }
            set {
                this.y_on_y_growth_forward_epsFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal average_mktcap {
            get {
                return this.average_mktcapField;
            }
            set {
                this.average_mktcapField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool average_mktcapSpecified {
            get {
                return this.average_mktcapFieldSpecified;
            }
            set {
                this.average_mktcapFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal median_mktcap {
            get {
                return this.median_mktcapField;
            }
            set {
                this.median_mktcapField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool median_mktcapSpecified {
            get {
                return this.median_mktcapFieldSpecified;
            }
            set {
                this.median_mktcapFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal _5_years_ADPS_growth_rate {
            get {
                return this._5_years_ADPS_growth_rateField;
            }
            set {
                this._5_years_ADPS_growth_rateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool _5_years_ADPS_growth_rateSpecified {
            get {
                return this._5_years_ADPS_growth_rateFieldSpecified;
            }
            set {
                this._5_years_ADPS_growth_rateFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal _1_year_ADPS_growth_rate {
            get {
                return this._1_year_ADPS_growth_rateField;
            }
            set {
                this._1_year_ADPS_growth_rateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool _1_year_ADPS_growth_rateSpecified {
            get {
                return this._1_year_ADPS_growth_rateFieldSpecified;
            }
            set {
                this._1_year_ADPS_growth_rateFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal payout_ratio {
            get {
                return this.payout_ratioField;
            }
            set {
                this.payout_ratioField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool payout_ratioSpecified {
            get {
                return this.payout_ratioFieldSpecified;
            }
            set {
                this.payout_ratioFieldSpecified = value;
            }
        }
    }
}
