// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>MSCIBarra_EquityIndex</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MSCIBarra_EquityIndex
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xml.mscibarra.com/ns/msci/deal/D98D")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.mscibarra.com/ns/msci/deal/D98D", IsNullable = false)]
    public partial class package_D98D
    {

        private List<package_D98DEntry> dataset_D98DField;

        public package_D98D()
        {
            this.dataset_D98DField = new List<package_D98DEntry>();
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable = false)]
        public List<package_D98DEntry> dataset_D98D
        {
            get
            {
                return this.dataset_D98DField;
            }
            set
            {
                this.dataset_D98DField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xml.mscibarra.com/ns/msci/deal/D98D")]
    public partial class package_D98DEntry
    {

        private System.DateTime calc_dateField;

        private string security_nameField;

        private decimal msci_timeseries_codeField;

        private decimal msci_issuer_codeField;

        private decimal msci_security_codeField;

        private string sedolField;

        private string sedol_next_dayField;

        private string cusipField;

        private string cusip_next_dayField;

        private string isinField;

        private string isin_next_dayField;

        private string ricField;

        private string ric_next_dayField;

        private string bb_tickerField;

        private string bb_ticker_next_dayField;

        private string barra_idField;

        private string micField;

        private string mic_next_dayField;

        private string china_stock_codeField;

        private string china_stock_code_ndField;

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime calc_date
        {
            get
            {
                return this.calc_dateField;
            }
            set
            {
                this.calc_dateField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string security_name
        {
            get
            {
                return this.security_nameField;
            }
            set
            {
                this.security_nameField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal msci_timeseries_code
        {
            get
            {
                return this.msci_timeseries_codeField;
            }
            set
            {
                this.msci_timeseries_codeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal msci_issuer_code
        {
            get
            {
                return this.msci_issuer_codeField;
            }
            set
            {
                this.msci_issuer_codeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal msci_security_code
        {
            get
            {
                return this.msci_security_codeField;
            }
            set
            {
                this.msci_security_codeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sedol
        {
            get
            {
                return this.sedolField;
            }
            set
            {
                this.sedolField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sedol_next_day
        {
            get
            {
                return this.sedol_next_dayField;
            }
            set
            {
                this.sedol_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cusip
        {
            get
            {
                return this.cusipField;
            }
            set
            {
                this.cusipField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cusip_next_day
        {
            get
            {
                return this.cusip_next_dayField;
            }
            set
            {
                this.cusip_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string isin
        {
            get
            {
                return this.isinField;
            }
            set
            {
                this.isinField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string isin_next_day
        {
            get
            {
                return this.isin_next_dayField;
            }
            set
            {
                this.isin_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ric
        {
            get
            {
                return this.ricField;
            }
            set
            {
                this.ricField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ric_next_day
        {
            get
            {
                return this.ric_next_dayField;
            }
            set
            {
                this.ric_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bb_ticker
        {
            get
            {
                return this.bb_tickerField;
            }
            set
            {
                this.bb_tickerField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bb_ticker_next_day
        {
            get
            {
                return this.bb_ticker_next_dayField;
            }
            set
            {
                this.bb_ticker_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string barra_id
        {
            get
            {
                return this.barra_idField;
            }
            set
            {
                this.barra_idField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mic
        {
            get
            {
                return this.micField;
            }
            set
            {
                this.micField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mic_next_day
        {
            get
            {
                return this.mic_next_dayField;
            }
            set
            {
                this.mic_next_dayField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string china_stock_code
        {
            get
            {
                return this.china_stock_codeField;
            }
            set
            {
                this.china_stock_codeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string china_stock_code_nd
        {
            get
            {
                return this.china_stock_code_ndField;
            }
            set
            {
                this.china_stock_code_ndField = value;
            }
        }
    }
}
