// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>MSCIBarra_EquityIndex</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MSCIBarra_EquityIndex
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xml.mscibarra.com/ns/msci/deal/D16D")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://xml.mscibarra.com/ns/msci/deal/D16D", IsNullable = false)]
    public partial class package_D16D
    {

        private List<package_D16DEntry> dataset_D16DField;

        public package_D16D()
        {
            this.dataset_D16DField = new List<package_D16DEntry>();
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable = false)]
        public List<package_D16DEntry> dataset_D16D
        {
            get
            {
                return this.dataset_D16DField;
            }
            set
            {
                this.dataset_D16DField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://xml.mscibarra.com/ns/msci/deal/D16D")]
    public partial class package_D16DEntry
    {

        private System.DateTime calc_dateField;

        private string security_nameField;

        private decimal msci_timeseries_codeField;

        private decimal msci_security_codeField;

        private decimal msci_dividend_codeField;

        private string bb_tickerField;

        private string sedolField;

        private string cusipField;

        private string isinField;

        private string dividend_descriptionField;

        private decimal correction_flagField;

        private bool correction_flagFieldSpecified;

        private System.DateTime xd_dateField;

        private System.DateTime reinvestment_in_index_dateField;

        private decimal unadjusted_dividend_amountField;

        private decimal adjusted_grs_dividend_amountField;

        private decimal adjusted_net_dividend_amountField;

        private string dividend_ISO_currency_symbolField;

        private decimal dividend_sub_unitField;

        private bool dividend_sub_unitFieldSpecified;

        private decimal dividend_adjustment_factorField;

        private bool dividend_adjustment_factorFieldSpecified;

        private decimal dTR_number_of_sharesField;

        private bool dTR_number_of_sharesFieldSpecified;

        private decimal withholding_tax_rateField;

        private bool withholding_tax_rateFieldSpecified;

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime calc_date
        {
            get
            {
                return this.calc_dateField;
            }
            set
            {
                this.calc_dateField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string security_name
        {
            get
            {
                return this.security_nameField;
            }
            set
            {
                this.security_nameField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal msci_timeseries_code
        {
            get
            {
                return this.msci_timeseries_codeField;
            }
            set
            {
                this.msci_timeseries_codeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal msci_security_code
        {
            get
            {
                return this.msci_security_codeField;
            }
            set
            {
                this.msci_security_codeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal msci_dividend_code
        {
            get
            {
                return this.msci_dividend_codeField;
            }
            set
            {
                this.msci_dividend_codeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bb_ticker
        {
            get
            {
                return this.bb_tickerField;
            }
            set
            {
                this.bb_tickerField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sedol
        {
            get
            {
                return this.sedolField;
            }
            set
            {
                this.sedolField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cusip
        {
            get
            {
                return this.cusipField;
            }
            set
            {
                this.cusipField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string isin
        {
            get
            {
                return this.isinField;
            }
            set
            {
                this.isinField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dividend_description
        {
            get
            {
                return this.dividend_descriptionField;
            }
            set
            {
                this.dividend_descriptionField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal correction_flag
        {
            get
            {
                return this.correction_flagField;
            }
            set
            {
                this.correction_flagField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool correction_flagSpecified
        {
            get
            {
                return this.correction_flagFieldSpecified;
            }
            set
            {
                this.correction_flagFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime xd_date
        {
            get
            {
                return this.xd_dateField;
            }
            set
            {
                this.xd_dateField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime reinvestment_in_index_date
        {
            get
            {
                return this.reinvestment_in_index_dateField;
            }
            set
            {
                this.reinvestment_in_index_dateField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal unadjusted_dividend_amount
        {
            get
            {
                return this.unadjusted_dividend_amountField;
            }
            set
            {
                this.unadjusted_dividend_amountField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal adjusted_grs_dividend_amount
        {
            get
            {
                return this.adjusted_grs_dividend_amountField;
            }
            set
            {
                this.adjusted_grs_dividend_amountField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal adjusted_net_dividend_amount
        {
            get
            {
                return this.adjusted_net_dividend_amountField;
            }
            set
            {
                this.adjusted_net_dividend_amountField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dividend_ISO_currency_symbol
        {
            get
            {
                return this.dividend_ISO_currency_symbolField;
            }
            set
            {
                this.dividend_ISO_currency_symbolField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dividend_sub_unit
        {
            get
            {
                return this.dividend_sub_unitField;
            }
            set
            {
                this.dividend_sub_unitField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dividend_sub_unitSpecified
        {
            get
            {
                return this.dividend_sub_unitFieldSpecified;
            }
            set
            {
                this.dividend_sub_unitFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal dividend_adjustment_factor
        {
            get
            {
                return this.dividend_adjustment_factorField;
            }
            set
            {
                this.dividend_adjustment_factorField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dividend_adjustment_factorSpecified
        {
            get
            {
                return this.dividend_adjustment_factorFieldSpecified;
            }
            set
            {
                this.dividend_adjustment_factorFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal DTR_number_of_shares
        {
            get
            {
                return this.dTR_number_of_sharesField;
            }
            set
            {
                this.dTR_number_of_sharesField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DTR_number_of_sharesSpecified
        {
            get
            {
                return this.dTR_number_of_sharesFieldSpecified;
            }
            set
            {
                this.dTR_number_of_sharesFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal withholding_tax_rate
        {
            get
            {
                return this.withholding_tax_rateField;
            }
            set
            {
                this.withholding_tax_rateField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool withholding_tax_rateSpecified
        {
            get
            {
                return this.withholding_tax_rateFieldSpecified;
            }
            set
            {
                this.withholding_tax_rateFieldSpecified = value;
            }
        }
    }
}
