// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>MSCIBarra_EquityIndex.core_amer_daily</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MSCIBarra_EquityIndex.core_amer_daily {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.mscibarra.com/ns/msci/deal/D80A.CTY")]
    [System.Xml.Serialization.XmlRootAttribute("package_D80A.CTY", Namespace="http://xml.mscibarra.com/ns/msci/deal/D80A.CTY", IsNullable=false)]
    public partial class package_D80ACTY {
        
        private List<package_D80ACTYEntry> dataset_D80ACTYCField;
        
        private List<package_D80ACTYEntry1> dataset_D80ACTYIField;
        
        private List<package_D80ACTYEntry2> dataset_D80ACTYWField;
        
        public package_D80ACTY() {
            this.dataset_D80ACTYWField = new List<package_D80ACTYEntry2>();
            this.dataset_D80ACTYIField = new List<package_D80ACTYEntry1>();
            this.dataset_D80ACTYCField = new List<package_D80ACTYEntry>();
        }
        
        [System.Xml.Serialization.XmlArrayAttribute("dataset_D80A.CTY.C", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
        public List<package_D80ACTYEntry> dataset_D80ACTYC {
            get {
                return this.dataset_D80ACTYCField;
            }
            set {
                this.dataset_D80ACTYCField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute("dataset_D80A.CTY.I", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
        public List<package_D80ACTYEntry1> dataset_D80ACTYI {
            get {
                return this.dataset_D80ACTYIField;
            }
            set {
                this.dataset_D80ACTYIField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute("dataset_D80A.CTY.W", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
        public List<package_D80ACTYEntry2> dataset_D80ACTYW {
            get {
                return this.dataset_D80ACTYWField;
            }
            set {
                this.dataset_D80ACTYWField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.mscibarra.com/ns/msci/deal/D80A.CTY")]
    public partial class package_D80ACTYEntry {
        
        private System.DateTime calc_dateField;
        
        private string iSO_country_symbolField;
        
        private string country_nameField;
        
        private string bond_yield_nameField;
        
        private decimal bond_yieldField;
        
        private bool bond_yieldFieldSpecified;
        
        private decimal bond_yield_change_eom01mField;
        
        private bool bond_yield_change_eom01mFieldSpecified;
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime calc_date {
            get {
                return this.calc_dateField;
            }
            set {
                this.calc_dateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ISO_country_symbol {
            get {
                return this.iSO_country_symbolField;
            }
            set {
                this.iSO_country_symbolField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string country_name {
            get {
                return this.country_nameField;
            }
            set {
                this.country_nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bond_yield_name {
            get {
                return this.bond_yield_nameField;
            }
            set {
                this.bond_yield_nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal bond_yield {
            get {
                return this.bond_yieldField;
            }
            set {
                this.bond_yieldField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bond_yieldSpecified {
            get {
                return this.bond_yieldFieldSpecified;
            }
            set {
                this.bond_yieldFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal bond_yield_change_eom01m {
            get {
                return this.bond_yield_change_eom01mField;
            }
            set {
                this.bond_yield_change_eom01mField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bond_yield_change_eom01mSpecified {
            get {
                return this.bond_yield_change_eom01mFieldSpecified;
            }
            set {
                this.bond_yield_change_eom01mFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.mscibarra.com/ns/msci/deal/D80A.CTY")]
    public partial class package_D80ACTYEntry1 {
        
        private System.DateTime calc_dateField;
        
        private decimal msci_index_codeField;
        
        private string index_nameField;
        
        private string region_codeField;
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime calc_date {
            get {
                return this.calc_dateField;
            }
            set {
                this.calc_dateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal msci_index_code {
            get {
                return this.msci_index_codeField;
            }
            set {
                this.msci_index_codeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index_name {
            get {
                return this.index_nameField;
            }
            set {
                this.index_nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string region_code {
            get {
                return this.region_codeField;
            }
            set {
                this.region_codeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.mscibarra.com/ns/msci/deal/D80A.CTY")]
    public partial class package_D80ACTYEntry2 {
        
        private System.DateTime calc_dateField;
        
        private decimal msci_index_codeField;
        
        private string iSO_country_symbolField;
        
        private decimal country_weightField;
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime calc_date {
            get {
                return this.calc_dateField;
            }
            set {
                this.calc_dateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal msci_index_code {
            get {
                return this.msci_index_codeField;
            }
            set {
                this.msci_index_codeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ISO_country_symbol {
            get {
                return this.iSO_country_symbolField;
            }
            set {
                this.iSO_country_symbolField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal country_weight {
            get {
                return this.country_weightField;
            }
            set {
                this.country_weightField = value;
            }
        }
    }
}
