//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FGA.Automate.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FGA.Automate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;xsl:stylesheet version=&quot;1.0&quot;
        ///    xmlns=&quot;urn:schemas-microsoft-com:office:spreadsheet&quot;
        ///    xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; 
        /// xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot;
        /// xmlns:user=&quot;urn:my-scripts&quot;
        /// xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;
        /// xmlns:x=&quot;urn:schemas-microsoft-com:office:excel&quot;
        /// xmlns:ss=&quot;urn:schemas-microsoft-com:office:spreadsheet&quot; &gt; 
        /// 
        ///&lt;xsl:template match=&quot;/&quot;&gt;
        ///  &lt;Workbook xmlns=&quot;urn:schemas-microsoft-com:office:spreadsheet&quot;
        ///    xmlns:o=&quot;urn:schemas-microso [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Excel {
            get {
                return ResourceManager.GetString("Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;xsl:stylesheet version=&quot;1.0&quot;
        ///    xmlns=&quot;urn:schemas-microsoft-com:office:spreadsheet&quot;
        ///    xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; 
        /// xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot;
        /// xmlns:user=&quot;urn:my-scripts&quot;
        /// xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;
        /// xmlns:x=&quot;urn:schemas-microsoft-com:office:excel&quot;
        /// xmlns:ss=&quot;urn:schemas-microsoft-com:office:spreadsheet&quot; &gt; 
        /// 
        ///&lt;xsl:template match=&quot;/&quot;&gt;
        ///  &lt;Workbook xmlns=&quot;urn:schemas-microsoft-com:office:spreadsheet&quot;
        ///    xmlns:o=&quot;urn:schemas-microso [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Excel_type {
            get {
                return ResourceManager.GetString("Excel_type", resourceCulture);
            }
        }
    }
}
